version: '3'
services:
  mongo:
    image: mongo
    container_name: reactive_web_sample.mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'root'
      MONGO_INITDB_DATABASE: 'test'